# -*- coding: utf-8 -*-
"""model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15CuwXj1nqpvzmRdEH5CqxXXbzGrGYzYI
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn import tree
import pickle

# it classification problem with 3 classes 
#load data
iris = datasets.load_iris()
x = iris.data
y = iris.target
labels ={
  0: "setosa",
  1: "versicolor",
  2: "virginica"
}
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.5)

#build classifier
classifier = tree.DecisionTreeClassifier()
classifier.fit(x_train,y_train)
predictions = classifier.predict(x_test)

#store model
pickle.dump(classifier,open('model.pkl','wb'))

#test model
model = pickle.load(open('model.pkl','rb'))
x = [[4.3, 3. , 1.1, 0.1]]
predict = model.predict(x)
print(labels[predict[0]])